apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: yolo
  labels:
    app: yolo-demo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-demo-client
  template:
    metadata:
      labels:
        app: yolo-demo-client
    spec:
      containers:
      - name: yolo-demo-client
        image: docker.io/churong/yolo:latest
        command: ["/bin/sh"]
        args: ["-c", "python3 /app/edge_yolo_inference.py 10.233.100.172 9876"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/content
      volumes:
      - name: dataset-volume
        hostPath:
          path: /h/churongj/ACAI_Emulator/YOLOv3_Train_Inference/content
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: yolo
spec:
  selector:
    app: yolo-demo-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9876
