apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: yolo
  labels:
    app: yolo-demo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-demo-client
  template:
    metadata:
      labels:
        app: yolo-demo-client
    spec:
      containers:
      - name: file-transfer-client
        image: docker.io/hangruicao/yolo:clientv4
        command: ["/bin/sh"]
        args: ["-c", "python3 /app/edge_yolo_inference.py 10.233.58.87 9876"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: yolo
spec:
  selector:
    app: yolo-demo-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9876
