apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-{}
  namespace: yolo
  labels:
    app: yolo-demo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-demo-client
  template:
    metadata:
      labels:
        app: yolo-demo-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - phortx2
      containers:
      - name: yolo-demo-client-{}
        # image: docker.pdl.cmu.edu/acai_yolo:v2
        image: docker.io/churong/yolo:multi-pod-no-limit-retrain
        command: ["/bin/sh"]
        args: ["-c", "python3 /app/edge_yolo_inference.py {} 9876 edge_inf.log edge_update.log edge_inf.csv edge_update.csv 10 {}"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "20"
          limits:
            cpu: "20"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/content
        - name: log-volume
          mountPath: /app/logs
      volumes:
      - name: dataset-volume
        nfs:
          server: basket
          path: /users/churongj/ACAI_Emulator/YOLOv3_Train_Inference/content
      - name: log-volume
        nfs:
          server: basket
          path: /users/churongj/ACAI_Emulator/YOLOv3_Train_Inference/logs

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: yolo
spec:
  selector:
    app: yolo-demo-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9876
