apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth
spec:
  action: bandwidth
  mode: all
  selector:
    namespaces:
      - labeltest
  bandwidth:
    rate: '20mbps'
    limit: 20971520
    buffer: 100000