apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - labeltest
  delay:
    latency: '500ms'
    correlation: '0'
    jitter: '0ms'